import {
  Entity, PrimaryGeneratedColumn, Column, ManyToOne,
  CreateDateColumn, UpdateDateColumn, JoinColumn,
} from 'typeorm';
import { User } from '../../users/entities/user.entity';

export enum PlanStatus {
  ACTIVE = 'active',
  COMPLETED = 'completed',
  ARCHIVED = 'archived',
}

export enum FitnessGoal {
  LOSE_FAT = 'lose_fat',
  BUILD_MUSCLE = 'build_muscle',
  MAINTAIN = 'maintain',
  IMPROVE_ENDURANCE = 'improve_endurance',
}

@Entity('workout_plans')
export class WorkoutPlan {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @ManyToOne(() => User, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'user_id' })
  user: User;

  @Column({ name: 'user_id' })
  userId: string;

  @Column({ length: 255 })
  title: string;

  @Column({ type: 'text', nullable: true })
  description: string | null;

  @Column({ type: 'enum', enum: FitnessGoal })
  goal: FitnessGoal;

  @Column({ name: 'duration_weeks', type: 'smallint' })
  durationWeeks: number;

  @Column({ name: 'sessions_per_week', type: 'smallint' })
  sessionsPerWeek: number;

  @Column({ type: 'enum', enum: PlanStatus, default: PlanStatus.ACTIVE })
  status: PlanStatus;

  /** Full plan JSON generated by the AI service (stored for reproducibility). */
  @Column({ type: 'jsonb', nullable: true })
  planJson: Record<string, any> | null;

  @CreateDateColumn({ name: 'created_at' }) createdAt: Date;
  @UpdateDateColumn({ name: 'updated_at' }) updatedAt: Date;
}
